paths:
  input_dir: "./intervention_graph_creation/data/raw/ard_json"
  output_dir: "./intervention_graph_creation/data/processed"

falkordb:
  host: "localhost"
  port: 6379
  graph: "AISafetyIntervention"

embeddings:
  model: "text-embedding-3-large"
  batch_size: 256
