paths:
  input_dir: "./intervention_graph_creation/data/raw/test"
  output_dir: "./intervention_graph_creation/data/processed_ard_one"

falkordb:
  host: "localhost"
  port: 6379
  graph: "AISafetyIntervention"
