paths:
  input_dir: "./intervention_graph_creation/data/raw/ard_json"
  output_dir: "./intervention_graph_creation/data/processed"
  logs_dir: "./logs"
  extraction_error_dir: "./extraction_error"
  graph_error_dir: "./graph_error"

falkordb:
  host: "localhost"
  port: 6379
  graph: "AISafetyIntervention"

embeddings:
  model: "text-embedding-3-small"
  batch_size: 64
  max_cuncurrent_batches: 120