[project]
name = "aisafetyintervention-literatureextraction"
version = "0.1.0"
description = "2025 Eleuther AI Summer of Open AI Research program for project #5, Scientific Literature Knowledge Extraction Tool."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
