"""
Standalone B9 regeneration — Item 5 from step45_revision4_inputs.txt

Regenerates umap_interventions_consim1_clusters.png with proper UMAP-1/UMAP-2
axis labels (with value ranges) replacing the previous axis("off") version.

Also answers Item 5 question: why does umap_interventions_consim1.png look
different from umap_interventions_consim1_clusters.png?
  - umap_interventions_consim1.png: generated by phase2_step4_umap_plots.py
    Uses ALL ~19,791 VPN_consim1 nodes; metric="cosine"; shows raw point cloud
    colored by cluster assignment; axes visible with tick marks.
  - umap_interventions_consim1_clusters.png: generated by B9 in rev3_computations.py
    Uses MAX 200 sampled nodes per cluster (up to 8000 total); default euclidean
    metric on L2-normalized vectors; overlays cluster name labels at centroids.
    Previously had axis("off"). Now fixed to show UMAP-1/UMAP-2 with value ranges.
"""

import gc
import sys
import json
import pickle
import textwrap
import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

BASE = "/mnt/c/Users/malei/0_project_work/eleutherAI_SOAR_step1knowledgegraphcreation/AISafetyIntervention_LiteratureExtraction"
ROOT = f"{BASE}/graph_analysis"
RESULTS = f"{ROOT}/phase2_results"
PKL_DIR = f"{RESULTS}/step1_load_and_parse_umapwithoutlocalsatellites"
TABLES_DIR = f"{RESULTS}/step4_finalanalysis/step4_cluster_tables"
META_DIR = f"{RESULTS}/step4_finalanalysis/step4_metaclusters"
NAMING_DIR = f"{RESULTS}/step5_naming"
RAWPATHS_DIR = f"{ROOT}/phase1_rawpathsfiles"
STEP4_DIR = f"{RESULTS}/step4_finalanalysis"

print("=== B9 UMAP clusters regeneration (Item 5 fix) ===\n")

# ─── Load PKL files ───────────────────────────────────────────────────────────
print("Loading node_attrs.pkl ...")
with open(f"{PKL_DIR}/graph_node_attributes.pkl", "rb") as f:
    node_attrs = pickle.load(f)
print(f"  node_attrs: {len(node_attrs)} nodes")

print("Loading cluster_memberships.pkl ...")
with open(f"{PKL_DIR}/cluster_memberships.pkl", "rb") as f:
    cm = pickle.load(f)
print(f"  cluster_memberships: {len(cm)} keys")

print("Loading graph_edge_data.pkl (needed for sim_edge_set) ...")
with open(f"{PKL_DIR}/graph_edge_data.pkl", "rb") as f:
    edge_data = pickle.load(f)
print(f"  edge_data: {len(edge_data)} edges")


# ─── Build VPN_consim1 ────────────────────────────────────────────────────────
def cos_sim_from_score(s):
    return 1.0 - float(s) ** 2 / 2.0


path_file = f"{RAWPATHS_DIR}/paths_unconstrained_sim0.9.jsonl"
print("Building VPN_consim1 (Pass 1: vpn_unconstrained) ...")
vpn_unconstrained = set()
with open(path_file) as f:
    for line in f:
        obj = json.loads(line.strip())
        if isinstance(obj, dict) and "path" in obj:
            path = [int(x) for x in obj["path"]]
            if (
                int(node_attrs.get(path[-1], {}).get("intervention_maturity", 0) or 0)
                >= 3
            ):
                vpn_unconstrained.update(path)
print(f"  vpn_unconstrained: {len(vpn_unconstrained)} nodes")

print("Building sim_edge_set ...")
sim_edge_set = set()
for e in edge_data:
    if str(e.get("type", "")).upper() == "SIMILARITY":
        score = e.get("similarity_score")
        if score is not None and cos_sim_from_score(score) >= 0.9:
            try:
                s, tgt = int(e["source"]), int(e["target"])
                if s in vpn_unconstrained and tgt in vpn_unconstrained:
                    sim_edge_set.add((min(s, tgt), max(s, tgt)))
            except (ValueError, TypeError):
                pass
print(f"  sim_edge_set: {len(sim_edge_set)} pairs")

del edge_data
gc.collect()


def max_consec_sim(path_ids):
    max_run = run = 0
    for i in range(len(path_ids) - 1):
        a, b = int(path_ids[i]), int(path_ids[i + 1])
        if (min(a, b), max(a, b)) in sim_edge_set:
            run += 1
            if run > max_run:
                max_run = run
        else:
            run = 0
    return max_run


print("Building VPN_consim1 (Pass 2: consim1 filter) ...")
vpn = set()
with open(path_file) as f:
    for line in f:
        obj = json.loads(line.strip())
        if isinstance(obj, dict) and "path" in obj:
            path = [int(x) for x in obj["path"]]
            if (
                int(node_attrs.get(path[-1], {}).get("intervention_maturity", 0) or 0)
                < 3
            ):
                continue
            if max_consec_sim(path) <= 1:
                vpn.update(path)
print(f"  vpn_consim1: {len(vpn)} nodes")


# ─── Get cluster dict filtered to VPN ────────────────────────────────────────
def get_cluster_dict(node_type, ec=0.9, mode="unconstrained", algo="agglomerative"):
    result = {}
    for key, members in cm.items():
        try:
            e_float = float(key[0])
        except (ValueError, TypeError):
            continue
        if (
            abs(e_float - ec) < 1e-9
            and key[1] == mode
            and key[2] == node_type
            and key[3] == algo
        ):
            filtered = [nid for nid in members if nid in vpn]
            if filtered:
                result[int(key[4])] = filtered
    return result


def get_embedding(nid):
    emb = node_attrs[nid].get("embedding")
    if emb is None:
        return None
    if isinstance(emb, np.ndarray):
        v = emb.astype(np.float32)
    elif isinstance(emb, str):
        v = np.fromstring(emb.strip("<>"), sep=",", dtype=np.float32)
    else:
        v = np.array(emb, dtype=np.float32)
    n = np.linalg.norm(v)
    return v / n if n > 1e-9 else v


# ─── Load names and meta-assignments ─────────────────────────────────────────
def load_names(path):
    df = pd.read_csv(path)
    col = "final_name" if "final_name" in df.columns else "llm_name"
    return {int(r["cluster_id"]): str(r[col]) for _, r in df.iterrows()}


interv_names = load_names(f"{NAMING_DIR}/intervention_cluster_names_llm_v2.csv")

interv_meta_df = pd.read_csv(f"{META_DIR}/intervention_meta_assignments.csv")
interv_meta_map = dict(
    zip(interv_meta_df["cluster_id"].astype(str), interv_meta_df["meta_k10"])
)

# ─── B9: UMAP for intervention clusters ──────────────────────────────────────
print("\n=== B9: UMAP for intervention clusters (consim1) ===")

try:
    from umap import UMAP

    HAVE_UMAP = True
except ImportError:
    HAVE_UMAP = False
    print("  ERROR: umap-learn not available — cannot run B9")
    sys.exit(1)

interv_clusters = get_cluster_dict("intervention")
print(f"  Intervention clusters: {len(interv_clusters)}")
print(f"  Total VPN members: {sum(len(v) for v in interv_clusters.values())}")

cmap_plot = plt.cm.get_cmap("tab20", 40)
N_SAMPLE_PER_CLUSTER = 200

all_vecs = []
all_cids = []
for cid, members in sorted(interv_clusters.items()):
    sample = members[:N_SAMPLE_PER_CLUSTER]
    for nid in sample:
        v = get_embedding(nid)
        if v is not None:
            all_vecs.append(v)
            all_cids.append(cid)

print(f"  Total nodes for UMAP: {len(all_vecs)}")

X = np.array(all_vecs, dtype=np.float32)
print(f"  Running UMAP on {len(X)} nodes ...")
reducer = UMAP(n_components=2, random_state=42, n_neighbors=15, min_dist=0.1)
coords = reducer.fit_transform(X)

fig, ax = plt.subplots(figsize=(14, 11))
unique_cids = sorted(set(all_cids))
for cid in unique_cids:
    mask = np.array([c == cid for c in all_cids])
    ax.scatter(
        coords[mask, 0],
        coords[mask, 1],
        s=10,
        alpha=0.6,
        color=cmap_plot(cid % 40),
        label=f"I{cid}",
        zorder=2,
    )

for cid in unique_cids:
    mask = np.array([c == cid for c in all_cids])
    cx, cy = coords[mask, 0].mean(), coords[mask, 1].mean()
    label = "\n".join(textwrap.wrap(interv_names.get(cid, f"I{cid}"), width=20))
    ax.text(
        cx,
        cy,
        label,
        fontsize=4.5,
        ha="center",
        va="center",
        bbox=dict(facecolor="white", alpha=0.5, edgecolor="none", pad=0.5),
    )

ax.set_title(
    "Intervention Clusters — UMAP (consim1 qualifying nodes, colored by cluster)",
    fontsize=11,
    fontweight="bold",
)

x0, x1 = coords[:, 0].min(), coords[:, 0].max()
y0, y1 = coords[:, 1].min(), coords[:, 1].max()
ax.set_xlabel(f"UMAP-1  [{x0:.1f}, {x1:.1f}]", fontsize=9)
ax.set_ylabel(f"UMAP-2  [{y0:.1f}, {y1:.1f}]", fontsize=9)
ax.tick_params(labelsize=7)

plt.tight_layout()
out_path = f"{STEP4_DIR}/umap_interventions_consim1_clusters.png"
fig.savefig(out_path, dpi=130, bbox_inches="tight")
plt.close(fig)
print("  Saved: step4_finalanalysis/umap_interventions_consim1_clusters.png")

print("\n=== B9 UMAP clusters regeneration COMPLETE ===")
